name: CI
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
    
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build using Cocoapods
        run: |
          pod lib lint XS2AiOS.podspec --allow-warnings
