name: Release CI
on:
  release:
    types: [ published ]
    
jobs:
  publish:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push XS2AiOS.podspec
